//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace wxSharp
{
    public unsafe static partial class wxRemoveRef
    {
        [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct Internal
        {
        }
    }

    namespace Delegates
    {
        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_intPtr_charPtrPtr(global::System.IntPtr instance, int* arg1, char** arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate global::System.IntPtr Func_IntPtr_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate global::System.IntPtr Func_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate int Func_int_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate int Func_int_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, global::System.IntPtr arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_IntPtr_int_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, int arg2, global::System.IntPtr arg3, global::System.IntPtr arg4, global::System.IntPtr arg5);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_IntPtr_int_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, int arg2, global::System.IntPtr arg3, global::System.IntPtr arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate global::System.IntPtr Func_IntPtr_IntPtr_IntPtr_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, global::System.IntPtr arg3, global::System.IntPtr arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_int(global::System.IntPtr instance, int arg1);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate wxLayoutDirection Func_wxLayoutDirection_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate uint Func_uint_IntPtr_charPtr_uint_IntPtr_uint(global::System.IntPtr instance, char* arg1, uint arg2, global::System.IntPtr arg3, uint arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate uint Func_uint_IntPtr_sbytePtr_uint_IntPtr_uint(global::System.IntPtr instance, sbyte* arg1, uint arg2, global::System.IntPtr arg3, uint arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate uint Func_uint_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate uint Func_uint_IntPtr_charPtr_IntPtr_uint(global::System.IntPtr instance, char* arg1, global::System.IntPtr arg2, uint arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate uint Func_uint_IntPtr_sbytePtr_IntPtr_uint(global::System.IntPtr instance, sbyte* arg1, global::System.IntPtr arg2, uint arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate wxEventCategory Func_wxEventCategory_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, global::System.IntPtr arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate wxPoint.Internal Func_wxPoint_Internal_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate byte Func_byte_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_byte_byte_byte_byte(global::System.IntPtr instance, byte arg1, byte arg2, byte arg3, byte arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_IntPtr_int(global::System.IntPtr arg1, global::System.IntPtr instance, int arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_int_int_int(global::System.IntPtr instance, int arg1, int arg2, int arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_int(global::System.IntPtr instance, global::System.IntPtr arg1, int arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_wxBitmapType_int_int_int(global::System.IntPtr instance, global::System.IntPtr arg1, wxBitmapType arg2, int arg3, int arg4, int arg5);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_int_int_int_double(global::System.IntPtr instance, int arg1, int arg2, int arg3, double arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_wxBitmapType(global::System.IntPtr instance, global::System.IntPtr arg1, wxBitmapType arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_wxBitmapType_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, wxBitmapType arg2, global::System.IntPtr arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate double Func_double_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate wxSize.Internal Func_wxSize_Internal_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate uint Func_uint_IntPtr_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, global::System.IntPtr arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_IntPtr_bool_int(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, bool arg3, int arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_IntPtr_bool(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, bool arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_wxBitmapType_int(global::System.IntPtr instance, global::System.IntPtr arg1, wxBitmapType arg2, int arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_IntPtr_int(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, int arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate long Func_long_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate long Func_long_IntPtr_long_wxSeekMode(global::System.IntPtr instance, long arg1, wxSeekMode arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate sbyte Func_sbyte_IntPtr(global::System.IntPtr instance);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate global::System.IntPtr Func_IntPtr_IntPtr_IntPtr_uint(global::System.IntPtr instance, global::System.IntPtr arg1, uint arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate uint Func_uint_IntPtr_IntPtr_uint(global::System.IntPtr instance, global::System.IntPtr arg1, uint arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate char** Func_charPtrPtr_IntPtr_wxStreamProtocolType(global::System.IntPtr instance, wxStreamProtocolType arg1);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_sbyte(global::System.IntPtr instance, sbyte arg1);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_IntPtr_wxBitmapType_int_int_int(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, wxBitmapType arg3, int arg4, int arg5, int arg6);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_IntPtr_wxBitmapType_int_int(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, wxBitmapType arg3, int arg4, int arg5);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate bool Func_bool_IntPtr_IntPtr_IntPtr_wxBitmapType_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2, wxBitmapType arg3, global::System.IntPtr arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate global::System.IntPtr Func_IntPtr_IntPtr_IntPtr_IntPtr(global::System.IntPtr instance, global::System.IntPtr arg1, global::System.IntPtr arg2);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_IntPtr_uint_IntPtr_IntPtr(global::System.IntPtr arg1, global::System.IntPtr instance, uint arg2, global::System.IntPtr arg3, global::System.IntPtr arg4);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_uint_IntPtr_IntPtr(global::System.IntPtr instance, uint arg1, global::System.IntPtr arg2, global::System.IntPtr arg3);

        [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public unsafe delegate void Action_IntPtr_uint_IntPtr(global::System.IntPtr instance, uint arg1, global::System.IntPtr arg2);
    }
}
