name: CI

on: [push, pull_request]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-20.04, platform: x64, cxx: g++-9, cc: gcc-9 }
          - { os: macos-10.15, platform: x64, cxx: clang++, cc: clang }
          - { os: windows-2019, platform: x64, vs: 2019 }

    runs-on: ${{ matrix.config.os }}

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      VS_VERSION: ${{ matrix.config.vs }}
      PLATFORM: ${{ matrix.config.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Environment
        if: matrix.config.vs > 0
        shell: bash
        run: echo "/c/Program Files (x86)/Microsoft Visual Studio/$VS_VERSION/Enterprise/MSBuild/Current/Bin" >> $GITHUB_PATH

      - name: Fix intrin.h file
        if: matrix.config.vs > 0
        shell: powershell
        run: .github/workflows/intrin.ps1

      - name: Build wxWidgets
        shell: bash
        run: ./build-wx.sh -platform $PLATFORM
